CREATE TABLE NOTIFICATION(
	NOTIF_NUMBER		SERIAL				PRIMARY KEY,
	NOTIF_CONTENT		VARCHAR(255)		NOT NULL,
	NOTIF_DATE			DATE				DEFAULT CURRENT_TIMESTAMP,
	MEM_ID				INT					REFERENCES MEMBERS ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
)